import type { Metadata, Viewport } from "next";
import  localFont from 'next/font/local'


import "./globals.css";



const fraunces = localFont({
  src: './fonts/local/Fraunces_72pt_Soft-Light.ttf', // Path to your local file
  variable: '--font-fraunces',
  weight: '100',
  display: 'swap',
  // subsets: ['latin'] // Not needed for localFont
});

export const metadata: Metadata = {
  title: "Cabous en Jeanine",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png'
  }
  
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fraunces.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
