import type { Metadata, Viewport } from "next";
import {Fraunces, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fraunces = Fraunces(
  {
    subsets: ['latin'],
    variable: '--font-inner',
    weight: "100"
  }
)


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cabous en Jeanine",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png'
  }
  
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fraunces.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-thin`}
      >
        {children}
      </body>
    </html>
  );
}
